### ISSUE TITLE
Drop ready-to-use-downloads somewhere

### ISSUE THREAD

**Issue by Turysaz** [Turysaz/xylophone#3]
Game devs should be able to download a template for their OS somewhere

* [ ] Find hoster and set up download site
* [ ] Create WIN version
* [ ] Create Linux version
